# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-3.4.1
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-11-21T17:07:19Z"
  labels:
    app: musingtu
  name: musingtu
spec:
  containers:
  - env:
    - name: container
      value: oci
    image: localhost/ubi-httpd:latest
    name: musingtu
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      allowPrivilegeEscalation: true
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
      privileged: false
      readOnlyRootFilesystem: false
      seLinuxOptions: {}
    stdin: true
    workingDir: /
  dnsConfig: {}
status: {}

